In [1]:
import  numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

%matplotlib inline
sns.set(rc={'figure.figsize': [10, 10]}, font_scale=1.3)

In [2]:
df  = pd .read_csv('train.csv' ,index_col = 'PassengerId')
df

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Name      891 non-null    object 
 3   Sex       891 non-null    object 
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Ticket    891 non-null    object 
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object 
 10  Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB


In [4]:
from sklearn.impute import KNNImputer
imputer = KNNImputer()

In [5]:
df['Age'] = imputer.fit_transform(df[['Age']])
df['Age'].isnull().sum()

0

In [6]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [7]:
gender =  {'male':0 , 'female':1}

In [8]:
df['Sex'] =  df['Sex'].map(gender)

In [9]:
df['Sex'].value_counts()

0    577
1    314
Name: Sex, dtype: int64

In [10]:
df['Title'] =  df['Name'].apply(lambda x :x.split()[1])

In [11]:
def change_title(x):
    if x == "Mr.":
        return 1
    elif x == "Miss.":
        return  2 
    elif x == 'Mrs.':
        return 3
    elif x == 'Master.':
        return  4
    else :
        return 5 

In [12]:
df['Title'] = df['Title'].apply(change_title)

In [13]:
df['Title'].value_counts()

1    502
2    179
3    121
5     49
4     40
Name: Title, dtype: int64

In [14]:
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [15]:
embarked  = {'S':1,'C':2,'Q':3}
df['Embarked'] = df['Embarked'].map(embarked)

In [16]:
df['Embarked'].value_counts()

1.0    644
2.0    168
3.0     77
Name: Embarked, dtype: int64

In [17]:
df['Embarked'].fillna(3, inplace=True)

In [18]:
df.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name  Sex   Age  \
PassengerId                                                                 
1                                      Braund, Mr. Owen Harris    0  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0   
3                                       Heikkinen, Miss. Laina    1  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0   
5                                     Allen, Mr. William Henry    0  35.0   

             SibSp  Parch            Ticket     Fare Cabin  Embarked  Title  
PassengerId                                                                  
1                1      0         A/5 21171   7.2500   NaN       1.0      1  
2                1      0          PC 17599  71.2833   C85       2.0      3  
3                0      0  STON/O2. 3101282   7.9250   NaN       1.0      2  
4                1      0            113803  53.1000  C123       1.0      3  
5                0      0            373450   8.0500   NaN       1.0      1

In [19]:
df.drop(['Cabin','Name','Ticket','Fare'], axis = 1 , inplace = True )

In [21]:
df

Survived  Pclass  Sex        Age  SibSp  Parch  Embarked  Title
PassengerId                                                                 
1                   0       3    0  22.000000      1      0       1.0      1
2                   1       1    1  38.000000      1      0       2.0      3
3                   1       3    1  26.000000      0      0       1.0      2
4                   1       1    1  35.000000      1      0       1.0      3
5                   0       3    0  35.000000      0      0       1.0      1
...               ...     ...  ...        ...    ...    ...       ...    ...
887                 0       2    0  27.000000      0      0       1.0      5
888                 1       1    1  19.000000      0      0       1.0      2
889                 0       3    1  29.699118      1      2       1.0      2
890                 1       1    0  26.000000      0      0       2.0      1
891                 0       3    0  32.000000      0      0       3.0      1

[891 rows x 8 columns]

In [20]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked',
       'Title'],
      dtype='object')

In [22]:
df['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [24]:
from imblearn.over_sampling import SMOTE

x = df.drop('Survived', axis=1)
y = df['Survived']

# setting up testing and training sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=27)

In [25]:
sm = SMOTE(random_state=27)

In [28]:
x_train, y_train = sm.fit_resample(x_train, y_train)

In [29]:
scaler = StandardScaler()

scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, fbeta_score

In [34]:
models = {
    "LR": LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "SVC": SVC(),
    "DT": DecisionTreeClassifier(),
    "RF": RandomForestClassifier(),
    "XGB": XGBClassifier()
}

In [35]:
for name, model in models.items():
    print(f'Training Model {name} \n--------------')
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(f'Training Accuracy: {accuracy_score(model.predict(x_train), y_train)}')
    print(f'Testing Accuracy: {accuracy_score(y_pred, y_test)}')
    print(f'Testing Confusion Matrix: \n{confusion_matrix(y_pred, y_test)}')
    print(f'Testing Recall: {recall_score(y_pred, y_test)}')    
    print(f'Testing Precesion: {precision_score(y_pred, y_test)}')
    print(f'Testing F-1: {f1_score(y_pred, y_test)}')
    print(f'Testing F-Beta: {fbeta_score(y_pred, y_test, beta=0.5)}')
    print('-'*20)

Training Model LR 
--------------
Training Accuracy: 0.7951945080091534
Testing Accuracy: 0.7988826815642458
Testing Confusion Matrix: 
[[89 13]
 [23 54]]
Testing Recall: 0.7012987012987013
Testing Precesion: 0.8059701492537313
Testing F-1: 0.75
Testing F-Beta: 0.7826086956521738
--------------------
Training Model KNN 
--------------
Training Accuracy: 0.8638443935926774
Testing Accuracy: 0.8268156424581006
Testing Confusion Matrix: 
[[95 14]
 [17 53]]
Testing Recall: 0.7571428571428571
Testing Precesion: 0.7910447761194029
Testing F-1: 0.7737226277372262
Testing F-Beta: 0.7840236686390532
--------------------
Training Model SVC 
--------------
Training Accuracy: 0.8272311212814645
Testing Accuracy: 0.8268156424581006
Testing Confusion Matrix: 
[[93 12]
 [19 55]]
Testing Recall: 0.7432432432432432
Testing Precesion: 0.8208955223880597
Testing F-1: 0.7801418439716312
Testing F-Beta: 0.8040935672514621
--------------------
Training Model DT 
--------------
Training Accuracy: 0.943935926

C:\MyAnaconda\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[01:37:12] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy: 0.9267734553775744
Testing Accuracy: 0.8547486033519553
Testing Confusion Matrix: 
[[101  15]
 [ 11  52]]
Testing Recall: 0.8253968253968254
Testing Precesion: 0.7761194029850746
Testing F-1: 0.8
Testing F-Beta: 0.7854984894259818
--------------------


C:\MyAnaconda\lib\site-packages\xgboost\data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +


In [36]:
model = DecisionTreeClassifier()

model.fit(x_train, y_train)

DecisionTreeClassifier()

In [37]:
y_pred = model.predict(x_test)
y_pred

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0], dtype=int64)

In [38]:
y_test

PassengerId
433    1
11     1
39     0
748    1
315    0
      ..
334    0
248    1
719    0
230    0
569    0
Name: Survived, Length: 179, dtype: int64

In [39]:
test  = pd .read_csv('test.csv', index_col = 'PassengerId')
test

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
...             ...                                           ...     ...   
1305              3                            Spector, Mr. Woolf    male   
1306              1                  Oliva y Ocana, Dona. Fermina  female   
1307              3                  Saether, Mr. Simon Sivertsen    male   
1308              3                           Ware, Mr. Frederick    male   
1309              3                      Peter, Master. Michael J    male   

              Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
PassengerId                                                                   
892          34.5      0      0              330911    7.8292   NaN        Q  
893          47.0      1      0              363272    7.0000   NaN        S  
894          62.0      0      0              240276    9.6875   NaN        Q  
895          27.0      0      0              315154    8.6625   NaN        S  
896          22.0      1      1             3101298   12.2875   NaN        S  
...           ...    ...    ...                 ...       ...   ...      ...  
1305          NaN      0      0           A.5. 3236    8.0500   NaN        S  
1306         39.0      0      0            PC 17758  108.9000  C105        C  
1307         38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
1308          NaN      0      0              359309    8.0500   NaN        S  
1309          NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 10 columns]

In [40]:
def preprocess(x):
    from sklearn.impute import KNNImputer
    imputer = KNNImputer()
    x['Age'] = imputer.fit_transform(x[['Age']])
    
    gender =  {'male':0 , 'female':1}
    x['Sex'] =  x['Sex'].map(gender)
    
    x['Title'] = x['Name'].apply(lambda x :x.split()[1])
    
    def change_title(c):
        if c == "Mr.":
            return 1
        elif c == "Miss.":
            return  2 
        elif c == 'Mrs.':
            return 3
        elif c == 'Master.':
            return  4
        else :
            return 5 

    x['Title'] = x['Title'].apply(change_title)
    
    embarked  = {'S':1,'C':2,'Q':3}
    x['Embarked'] = x['Embarked'].map(embarked)
    x['Embarked'].fillna(3, inplace=True)
    
    x.drop(['Cabin','Name','Ticket','Fare'], axis = 1 , inplace = True )
    
    
    

In [41]:
preprocess(test)

In [42]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    int64  
 2   Age       418 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Embarked  418 non-null    int64  
 6   Title     418 non-null    int64  
dtypes: float64(1), int64(6)
memory usage: 26.1 KB


In [43]:
test = scaler.transform(test)
test

array([[ 0.92087414, -0.79985927,  0.34186766, ..., -0.4540084 ,
         2.48941537, -0.77063781],
       [ 0.92087414,  1.25021992,  1.28874514, ..., -0.4540084 ,
        -0.59194596,  1.00416442],
       [-0.24219522, -0.79985927,  2.42499811, ..., -0.4540084 ,
         2.48941537, -0.77063781],
       ...,
       [ 0.92087414, -0.79985927,  0.64486845, ..., -0.4540084 ,
        -0.59194596, -0.77063781],
       [ 0.92087414, -0.79985927,  0.02164054, ..., -0.4540084 ,
        -0.59194596, -0.77063781],
       [ 0.92087414, -0.79985927,  0.02164054, ...,  0.83851064,
         0.94873471,  1.89156553]])

In [44]:
prediction = model.predict(test)
prediction

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,

In [45]:
submission  = pd .read_csv('gender_submission.csv', index_col = 'PassengerId')
submission

Survived
PassengerId          
892                 0
893                 1
894                 0
895                 0
896                 1
...               ...
1305                0
1306                1
1307                0
1308                0
1309                0

[418 rows x 1 columns]

In [46]:
import joblib

In [47]:
joblib.dump(model, 'model.h5')
joblib.dump(scaler, 'scaler.h5')

['scaler.h5']